### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by FlinnBurgess** [HarveyHunt/TaxE#8]
This is a list of things that should have been completed by the end of section 2, and what needs to be completed by the end of section 3. 

**SECTION 2**
- [x] Map
- [x] Cities
- [x] Resources
- [x] Absolute Goals
- [x] Junctions (we have used our own knowledge that cities are doubled as junctions - this MUST be documented)

**SECTION 3**
- [x] Obstacles
- [x] Scoring - should support playability and entertainment value
- [ ] Quantifiable goals
- [ ] Updated documentation
- [ ] A website. Note that our last website didn't clearly point people to our documentation which I think was a major flaw, this needs to be kept in mind. Points will be lost if we don't have a website.

These are the most important things to be ticked off and can be achieved by ticking off items of the sections below.

This is based on the design document found at the following location: https://drive.google.com/file/d/0B4JuK-1u6R6nTmZBLXdkMVBVYUk/view
Please use the link to find more information on each point - the page number is located at the end of the point. Urgency is based on a cross-reference of the requirements for this section and whether the points addressed can be related to these requirements. "Pretty much pointless" is because either they add nothing of real importance to the game or they add something slightly important but with a disproportionate amount of effort to implement. 

**Important instructions:**
- **Make this page your homepage**
- Only tick an item off once you've discussed it with another team member and agreed that it is done
- Don't start work on any of the objectives without checking if it has already been started.
- If you start work on any of the objectives, please create a **separate** issue for it in Harvey's repo and add a link to that issue at the end of the point. This is to discuss any problems you might face while developing the feature, and will also be a place to write any necessary, thorough, documentation about why we made the decision to implement it and how we thought ahead about how we were going to do it.
- Once an objective has been finished, place a link after it pointing to the closed pull request, this will help with documenting anything that has not already been documented.

**URGENT**
- [x] IF TEXTURES CHANGE, update images in documents:
  + [x] Design doc: Train icons, route selection, city image, info box, homebase image, task list, penguin icon.
- [x] Remove BasicSleeper and replace it with "Sleeper" 619bfad5d58687ecba6ff96edbbcaf8c43919111
- [ ] Edit documentation
  + [ ] Remove references to XYG
  + [x] Design and GUI Report
  + [ ] Architecture
  + [x] User manual
- [x] Remove bezier curves #22 #23 
- [x] Refactor fuel #18 #20 
- [x] Loading and unloading cargo from a city. This is an extension of the city info point in the not urgent section, important with regards to goals. **(p.7)** #19 #34 26929cbd4aa357d9f649210adddef780cf43fd98
- [x] Implement scoring #9 #25 #27 
  + [x] Contact Richard about health system acting as scoring system. 
  + [x] Implement health damage based on influence **(p.10)**
  + [x] Tweak the code so that health depletes slower.
- [ ] Unit tests
  + [x] Fix map unit tests
  + [x] Gold generation
  + [ ] Un/Locking cities
  + [x] Tasks a94959ab2d043c6cf03b4b6103fc03be2af972dd
  + [ ] TaskFactory
  + [x] Tests for Influence d57683e6886080c1f6e01c74665d684416d490a9
  + [x] Player f01e7558e32c8db5aebf15ea4aab6d103a549111
- [x] Tasks need properly implementing **(p.8)** ed8864586cdd5da70fcdd09420220817fa5cee4a
  + [x] Tasks should be player independent **(p.11)**
  + [x] Update task menu with task information **(p.9)** #29 
  + [x] Remove a task when it has run out of turns 9c108d801052197ea72149e6bf7b0157fdac6d51
  + [x] Don't assign tasks for cities that have already been assigned. b68378c54075971e6305a43d574693adfd19ac22
  + [x] Correctly update a task's remaining turns in the task list. 96b741a2a53205f984f32c96cb0ddde7a23b328e
- [x] Complete implementation of city blocking #21 
  + [x] When selecting a path, a locked city's texture is incorrectly changed to the unselected texture
  + [x] New artwork for a locked city.
- [x] Implement cards #17 
  + [x] Block a city
  + [x] Extend train distance
- [ ] Implement generation of gold and other rewards (fuel, cards) based on city influence **(p.10/11)** #11 
  + [x] Gold generation
  + [x] Card rewards
  + [ ] Fuel rewards
- [x] Initialise a City's influence #16 

**NOT URGENT**
- [ ] Make the task list use a NotificationBox #30 
- [ ] Get rid of magic numbers (they are most obvious in gui).
- [x] When a route is cancelled, the route colours don't revert properly
- [x] Notify players when goal is complete. **(p.11)**
- [x] Double-click to display city info **(p.7, implementation already begun)**
- [ ] Double-click to display train info **(p.5)**
- [ ] Train catalogue, used when buy train is clicked. Can sort trains by different attributes or "star" a train to pin it to the top. **(p.6)**
- [x] Add more cargo types
- [x] Create new cargo icons **(see p.9 for style recommendation)** #40
- [ ] Trains condition depleting/train destruction **(p.12)**
- [x] Add textures for new trains 97ffcdbeea05f13c015bd4d63b7c6c0210537c51
- [ ] Replace player icons/images next to health bars

**PRETTY MUCH POINTLESS**
- [ ] Add extra detail/info to city images **(p.6)**
